"""add_cedula_and_address_to_patients

Revision ID: 60338b87b763
Revises: 7d0129f2b73f
Create Date: 2026-06-10 15:32:43.979828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60338b87b763'
down_revision: Union[str, Sequence[str], None] = '7d0129f2b73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cedula', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_cedula'), 'patients', ['cedula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_cedula'), table_name='patients')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'cedula')
    # ### end Alembic commands ###
