"""Agregar columna de permisos granulares a la tabla users

Revision ID: 89a2b4df114d
Revises: ff2121ec54bb
Create Date: 2026-07-26 14:39:09.145809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a2b4df114d'
down_revision: Union[str, Sequence[str], None] = 'ff2121ec54bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
