"""Evolucionar entidad documental para DMS

Revision ID: d36fc140ee6e
Revises: 8ecc61dfb846
Create Date: 2026-06-23 21:18:31.816585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36fc140ee6e'
down_revision: Union[str, Sequence[str], None] = '8ecc61dfb846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('folder_number', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documents_id'), 'patient_documents', ['id'], unique=False)
    op.alter_column('patients', 'cedula',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'cedula',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_patient_documents_id'), table_name='patient_documents')
    op.drop_table('patient_documents')
    # ### end Alembic commands ###
