"""Agregar columna cargo a la tabla patients

Revision ID: ff2121ec54bb
Revises: 91a33b1296ca
Create Date: 2026-07-15 17:38:03.029019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2121ec54bb'
down_revision: Union[str, Sequence[str], None] = '91a33b1296ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cargo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'cargo')
    # ### end Alembic commands ###
